services:
  # Backend application services (5 instances)
  app1:
    build: .
    environment:
      - SERVER_ID=app1
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app2:
    build: .
    environment:
      - SERVER_ID=app2
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app3:
    build: .
    environment:
      - SERVER_ID=app3
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app4:
    build: .
    environment:
      - SERVER_ID=app4
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app5:
    build: .
    environment:
      - SERVER_ID=app5
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  load_balance_network:
    driver: bridge