services:
  # Backend application services (5 instances)
  app1:
    build: .
    environment:
      - SERVER_ID=app1
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app2:
    build: .
    environment:
      - SERVER_ID=app2
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app3:
    build: .
    environment:
      - SERVER_ID=app3
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app4:
    build: .
    environment:
      - SERVER_ID=app4
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app5:
    build: .
    environment:
      - SERVER_ID=app5
      - PORT=3000
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy
      app4:
        condition: service_healthy
      app5:
        condition: service_healthy
    networks:
      - load_balance_network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://0.0.0.0/health-check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  load_balance_network:
    driver: bridge